### ISSUE TITLE
client_min_messages and 'SET time zone' incompatible with AWS Redshift: Make configurable?

### ISSUE THREAD

**Issue by findchris** [jruby/activerecord-jdbc-adapter#403]
Hi there.

AWS's Redshift is PostgreSQL under the hood, with some features restricted.  Trying to use this adapter with Redshift does not work, however, because reading and writing ```client_min_messages``` and issuing the ```SET time zone``` command is *not* supported.

If these two options were configurable (or potentially capable of handling failures), this adapter would successfully connect to Redshift.  I verified this by commenting out those lines locally (in ```lib/arjdbc/postgresql/adapter.rb```).

Cheers.

**Comment by Gauravshah** [comment]
created a silly gist https://gist.github.com/Gauravshah/a5774acdb75db6ce417b

**Comment by kares** [comment]
there's an attempt to fix this on the **1-3-stable** branch (will be in next 1.3 release) ... please for the future consider opening a PR instead of showcasing patches (should not be that hard esp. when knowing the places that need to get tuned). there's likely more incompatibilities and if someone concerned about Redshift did run the tests against it would likely reveal more issues.
