### ISSUE TITLE
Invalid SQL for DB2 with limit + offset + order when order refers to a column not in the result set

### ISSUE THREAD

**Issue by benissimo** [jruby/activerecord-jdbc-adapter#606]
See my comment on https://github.com/jruby/activerecord-jdbc-adapter/commit/b33063534c606b06c29b08e4f82b3f8fe5b061df
for details.

In brief, that commit introduced a limitation on ordering. Prior to that commit, you could join on another table and sort by the joined table's column(s) even if they weren't included in your result set. With that commit, doing so results in invalid SQL.

**Comment by kares** [comment]
https://github.com/jruby/activerecord-jdbc-adapter/commit/b33063534c606b06c29b08e4f82b3f8fe5b061df got reverted to NOT mangle with *OVER ( ORDER BY ... )* https://github.com/jruby/activerecord-jdbc-adapter/commit/0ec8f12d616f98e9cbd6a712a50b15a03ac808b5 as there was no test-case for the feature, use the test-case provided so that if it's re-introduced it's done in a more consistent way, thx!

**Comment by benissimo** [comment]
@kares Thanks for following up on this!
