### ISSUE TITLE
connection.execute returns strings for timestamp fields in postgres under rails 4.2

### ISSUE THREAD

**Issue by reger** [jruby/activerecord-jdbc-adapter#722]
Under Rails 4.2 timestamp fields are being returned as strings:

```
Loading development environment (Rails 4.2.6)
[1] pry(main)> fp = FuelPurchase.connection.execute("select created_at from fuel_purchases limit 1").first
   (3.0ms)  select created_at from fuel_purchases limit 1
=> {"created_at"=>"2015-12-18 08:18:45"}
[2] pry(main)> fp["created_at"].class
=> String
[3] pry(main)> fp = FuelPurchase.connection.execute("select * from fuel_purchases limit 1").first
   (1.0ms)  select * from fuel_purchases limit 1
=> {"id"=>48028535,
 "vehicle_id"=>765,
 "transacted_at"=>"2015-11-19 11:24:00",
 "vehicle_mileage"=>10876,
 "natural_units"=>#<BigDecimal:29ea5e0,'14.12',4(8)>,
 "gge_equivalent"=>#<BigDecimal:1c459c28,'14.12',4(8)>,
 "ghg_estimate"=>#<BigDecimal:6ffdbeef,'125.1283336',10(12)>,
 "fuel_station_id"=>837,
 "created_at"=>"2015-12-18 08:18:45",
 "fuel_payment_type_id"=>11,
 "fuel_type_code_id"=>5,
 "has_missed_opportunities"=>"f",
 "transaction_hidden"=>"f",
 "data_load_organization_id"=>3}
```

Under Rails 4.0.13 they were returned as Time objects:

```
Loading development environment (Rails 4.0.13)
[1] pry(main)> fp = FuelPurchase.connection.execute("select created_at from fuel_purchases limit 1").first
   (2.0ms)  select created_at from fuel_purchases limit 1
=> {"created_at"=>2015-12-18 08:18:45 UTC}
[2] pry(main)> fp["created_at"].class
=> Time
[3] pry(main)> fp = FuelPurchase.connection.execute("select * from fuel_purchases limit 1").first
   (5.0ms)  select * from fuel_purchases limit 1
=> {"id"=>48028535,
 "vehicle_id"=>765,
 "transacted_at"=>2015-11-19 11:24:00 UTC,
 "vehicle_mileage"=>10876,
 "natural_units"=>#<BigDecimal:4910afdf,'14.12',4(8)>,
 "gge_equivalent"=>#<BigDecimal:764db16c,'14.12',4(8)>,
 "ghg_estimate"=>#<BigDecimal:45cb5307,'125.1283336',10(12)>,
 "fuel_station_id"=>837,
 "created_at"=>2015-12-18 08:18:45 UTC,
 "fuel_payment_type_id"=>11,
 "fuel_type_code_id"=>5,
 "has_missed_opportunities"=>false,
 "transaction_hidden"=>false,
 "data_load_organization_id"=>3}
```

When updating to 4.2 this will obviously break anything in existing code expecting a Time object.

It looks like other data types (integer, big decimal) are being returned as the expected data type under 4.2.6. Booleans seem to exhibiting the same problem in 4.2.6 vs 4.0.13 as well.

We're seeing this with versions 1.3.17 and 1.3.20 of the adapter.
##

**Comment by GUI** [comment]
It looks like this was possibly an intentional change in behavior for Rails 4.2 in activerecord-jdbc-adapter v1.3.18 (see 07c646968922bebcbc4bdb07b33beab2a971c5bb). Results from ActiveRecord models will still get typecast as datetimes and booleans by functionality built into ActiveRecord. However, for any raw queries against the connection adapter that don't involve ActiveRecord (eg, `connection.select_all` or `connection.execute`), these now return strings for datetimes and booleans by default under Rails 4.2 and activerecord-jdbc-adapter.

You can restore the pre-4.2 typecasting functionality for raw queries by enabling these options (in a file like `config/initializers/arjdbc.rb`):

```ruby
ActiveRecord::ConnectionAdapters::PostgreSQLJdbcConnection.raw_date_time = false
ActiveRecord::ConnectionAdapters::PostgreSQLJdbcConnection.raw_boolean = false
```

However, this does affect all queries, including normal ActiveRecord results (not just the queries your explicitly making on the raw connection). I'm not exactly sure what the differences in typecasting between ARJDBC's implementation and ActiveRecord's built-in handling would be.
