### ISSUE TITLE
Fix broken AR5 support for MSSQL

### ISSUE THREAD

**Issue by jayjlawrence** [jruby/activerecord-jdbc-adapter#784]
I am starting this issue in hopes of playing a lead role in resolving the state of MS SQL support in AR5. I did have a look at the code and it seems that the MS SQL adapter is unique in that it more heavily overrides base classes than other adapters. As well there has been a few attempts such as SqlServerNG that further complicate studying the code. I had a brief exchange with another developer on what should be done.

I wonder if this is at the state where it would be faster/easier to rebuild the MS SQL fresh from the base JDBC code? I recognize that not every MS SQL feature would be supported immediately but for those of us who are looking for basic CRUD and joins on an MS SQL database this would be satisfactory.

Any recommendations on moving forward with establishing AR5 support for MS SQL? This feature is core to my work and so I need it and will be committed to making it happen one way or the other.

**Comment by enebo** [comment]
@jayjlawrence Thanks for stepping up on this.  Our original plan was to drop all but the base three adapters but if we can find someone who will get MSSQL adapter working then we are happy to keep it supported.

I think you could try starting fresh or use the existing classes.  Both have advantages and disadvantages.  I think in the sharing vein some of the basic methods should mostly work and they also interact with the Ruby side of things.  I am de-versioning (removing older version checks) on the rails5 branch.  I would recommend considering this decision from that branch.

If you do start fresh then it will be really cool to see if you make any different decisions.  AR-JDBC as a design is very old now.

**Comment by jayjlawrence** [comment]
@enbo Thanks for the followup - really appreciated. Yes I will *need* MSSQL support for my application for a variety of reasons and I'd like to move to Rails 5 - so consider me locked in to make this happen one way or the other.

My thought is to build a Rails5 only version of MSSQL that tries to get close up to the base code provided by JDBC so I'll build off of the rails-5 branch for sure. I did stick my nose into the existing code but so much is overridden that it will require very in-depth understanding of the parent code (in AREL as well as ARJDBC) which - well - a lot to take in! 

I'm going to do some experiments and followup with some results. Hopefully other MSSQL users chime in here as well. a) would like some help, and b) want to make sure their interests are heard.

**Comment by jayjlawrence** [comment]
@enebo - one question what are the 'base three'? SQLite, MySQL and Postegres?

**Comment by enebo** [comment]
@jayjlawrence yeah sorry those three.   Basically the main ones Rails supports.  Honestly supporting other may not be a ton of work but we are so far behind on this we decided to scale back in an attempt to be better about keeping up.

**Comment by kares** [comment]
@jayjlawrence do not recommend you start fresh (you could give it a try but have a dead-line up front on how much you will spend there) since you will eventually need to hook into AREL anyways due how MS-SQL's SQL engine works e.g. to get limit/offset working you will need to rewrite the query.

despite being "un-maintained" code, last time I checked (4.2 support) MS-SQL adapter was still doing better, in being able to correctly generate certain kinds of sophisticated queries, than the native SQLServer adapter out there. also if its intended to stay supported NONE should break :)

**Comment by jayjlawrence** [comment]
@kares thanks for the input - I'm going to assess both routes and will follow up early next week.

**Comment by mbramire** [comment]
@jayjlawrence Hey Jay, I share your interest in moving up to rails 5 but also rely on a solid MsSQL adapter for jRuby. Any update?

**Comment by jayjlawrence** [comment]
@mbramire I've been swamped at this end ... definitely thinking about it in the background. Do you have any resources that you might be able to bring to the table to help move things along?

**Comment by mbramire** [comment]
@jayjlawrence I might have to find some soon 😄 . I'll let you know if anything transpires on our end, but for now we are taking a wait and see.

**Comment by rdubya** [comment]
I'm working on the postgres adapter right now, but I plan on putting time into MSSQL once that is wrapped up. Not sure how much time I'll have over the next couple months but we can't upgrade to Rails 5 until its done either so I'll definitely be spending time on it.

**Comment by seizmo** [comment]
Hi there,

is someone working on this or has made some inroads which the can share as a starting point? I tried to get the MSSQL adapter running with Rails 5.1.6 but it doesn't even start (for various reasons like non existing/renamed methods, missing constant, changed method signatures, etc). Is there some kind of documentation which parts of the adapter need to be adapted to work with AR5? I would like to try to get MS SQL at least in a working state (even if some more exotic queries might not work) because otherwise we are essentially stuck with Rails 4 forever.

**Comment by rdubya** [comment]
Hey @seizmo, working on this unfortunately took a back seat to getting a postgres version released that supports 5.1 and now I'm busy with other projects at work so haven't managed to get back to it. I had hoped to try to potentially make use of the https://github.com/rails-sqlserver/activerecord-sqlserver-adapter gem and set up activerecord-jdbcmssql-adapter as a driver for it, but other than that I haven't dug into it too much. That may be more work than just getting the adapter working in its current state though. The biggest hurdle is probably that they rewrote how types work in Rails 5.

There unfortunately isn't any documentation about specific pieces that need updated.

It looks like it will take a little work at this point to get the rails tests to run against the mssql adapter, so the best first step might be to run the test suite for this project and just see if you can get it to even load/start. A bunch of the tests in there are likely to be Rails 3 or 4 specific so it's expected that there will likely be multiple tests that fail, but at least getting it so the test suite can start would be good.

You'll probably want to work off of the 51-stable branch or 50-stable branch since master is now targeting Rails 5.2 and doesn't have basic support for the big 3 adapters yet.

We need this implemented so we can get off of 4 as well so if you decide to dig into it I'd be more than happy to answer questions or provide whatever help I can.

**Comment by rdubya** [comment]
Nice find, if that gets merged in there probably won't be any reason to support mssql in this project anymore.

**Comment by rdubya** [comment]
This is now available as [activerecord-jdbcsqlserver-adapter](https://rubygems.org/gems/activerecord-jdbcsqlserver-adapter). It currently supports AR 5.0 and 5.1. 5.2 support will hopefully be coming before the end of the year. If you would like to see ActiveRecord 6.0 support please contribute to https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/tree/6-0-dev. We will then pull those changes into activerecord-jdbcsqlserver-adapter.
